### ISSUE TITLE
[Feature Request] Allow undo when using reset button

### ISSUE THREAD

**Issue by Barry0901C** [Merrit/unit_bargain_hunter#34]
Have it give you time to stop it from erasing everything

**Comment by Merrit** [comment]
Great idea! Thanks for opening the issue :grin:

**Comment by Merrit** [comment]
I am wondering if we need a reset button at all, now that the app supports multiple sheets.

It made sense back when it only had the one set of items, however now I am thinking rather than using the reset button it would be more pragmatic to:

- Remove excess item cards
- Delete the current sheet
- Start a new sheet

Here is an idea of what that could like like:

![image](https://user-images.githubusercontent.com/9575627/170844163-03f3488a-c1e3-4be5-9953-e8020a1525f7.png)

![image](https://user-images.githubusercontent.com/9575627/170844166-def553f7-3fa7-44d4-8d90-0abdf1d7c31f.png)

@Barry0901C What do you think?

**Comment by Barry0901C** [comment]
I like that idea. The odds of wanting to reset a sheet are slim… most likely would just delete a sheet once it’s so longer needed.

**Comment by Merrit** [comment]
Cool, we will go with that then. Thanks :grinning:
