### ISSUE TITLE
Website link broken

### ISSUE THREAD

**Issue by m3thm4th** [Merrit/unit_bargain_hunter#84]
The [link](https://merritt.codes/bargain/) this project points to is broken

**Comment by Merrit** [comment]
How so? It seems to work on my end:

![image](https://github.com/user-attachments/assets/90daaa95-9ade-4fe4-b9c7-680373007546)

**Comment by Merrit** [comment]
I think I see the issue. Please try [this link](https://merritt.codes/bargain)  and see if it works for you.

**Comment by Merrit** [comment]
What browser adds the trailing slash automatically? I don't see such behaviour on Firefox or Chrome, on Linux.

**Comment by Merrit** [comment]
Seems to be a quirk of the backend that having a trailing slash causes issues yeah, depending on where the site is hosted.

Since the link without the extra backslash works for both of us, I've gone ahead and updated the links to conform to that.

Thanks for opening the issue and letting me know about the problem! :blue_heart:

**Comment by Merrit** [comment]
It happens if you navigate to https://merritt.codes/bargain ?

or from a specific link?

**Comment by Merrit** [comment]
Right, that's with the trailing slash. That's an upstream 3rd party issue, so I updated all the links (on the website, in the repo) to a version without the trailing slash, so the links users actually click on should be okay now. Did I miss any?

**Comment by Merrit** [comment]
Yep, I missed that one. Fixed now. Thanks! :)
